import moment from "moment"
import { News, Stock, TimeSeriesData, TimeSeriesFrequence} from "../../types/Stock";
import {UserStocksSearchHistory} from "../../types/UserStocksSearchHistory";

function generateItens<T>(quantity: number, item: T): Array<T> {
    const result: Array<T> = []
    for (let i = 0 ; i < quantity; i++) {
        result.push(item)
    }
    return result
}

function generateMonthlyTimeSeries(quantity: number): TimeSeriesData {
    const results: TimeSeriesData = {}

    for (let i = 0 ; i < quantity; i++) {
        const month = moment().subtract(i, "months")

        results[month.format("YYYY-MM-DD")] = {
            open: Math.random(),
            high: Math.random(),
            low: Math.random(),
            volume: Math.random(),
            close: Math.random(),
        }
    }

    return results;
}

export const userStocksMockData: UserStocksSearchHistory[] = [
    {
        "symbol": "IBM",
        "name": "International Business Machines Corp",
        "date": new Date("2024-12-02 20:51:03.273567")
    },
    {
        "symbol": "GPN",
        "name": "Global Payments Inc",
        "date": new Date("2024-12-02 20:51:23.465699")
    }
]

export const stocksMockData: Stock[] = [
    {
        symbol: "IBM",
        newsFeed: generateItens(
            20,
            {
                title: "Log Management Market size is set to grow by USD 2.13 billion from 2023-2027, Growing demand from IT sector boost the market, Technavio - PR Newswire",
                url: "https://www.prnewswire.com/news-releases/log-management-market-size-is-set-to-grow-by-usd-2-13-billion-from-2023-2027--growing-demand-from-it-sector-boost-the-market-technavio-302195576.html",
                timePublished: moment("20240712T203000"),
                source: "PR Newswire",
                sourceDomain: "www.prnewswire.com",
                summary: "Log Management Market size is set to grow by USD 2.13 billion from 2023-2027, Growing demand from IT sector boost the market, Technavio PR ...",
                flags: [
                    {
                        name: "Earnings",
                        relevance: 0.108179
                    },
                    {
                        name: "Technology",
                        relevance: 0.5
                    },
                    {
                        name: "Manufacturing",
                        relevance: 0.5
                    }
                ]
            } as News,
        ),
        overview: {
            name: "International Business Machines",
            description: "International Business Machines Corporation (IBM) is an American multinational technology company headquartered in Armonk, New York, with operations in over 170 countries. The company began in 1911, founded in Endicott, New York, as the Computing-Tabulating-Recording Company (CTR) and was renamed International Business Machines in 1924. IBM is incorporated in New York. IBM produces and sells computer hardware, middleware and software, and provides hosting and consulting services in areas ranging from mainframe computers to nanotechnology. IBM is also a major research organization, holding the record for most annual U.S. patents generated by a business (as of 2020) for 28 consecutive years. Inventions by IBM include the automated teller machine (ATM), the floppy disk, the hard disk drive, the magnetic stripe card, the relational database, the SQL programming language, the UPC barcode, and dynamic random-access memory (DRAM). The IBM mainframe, exemplified by the System/360, was the dominant computing platform during the 1960s and 1970s.",
            country: "USA",
            sector: "TECHNOLOGY",
            industry: "COMPUTER & OFFICE EQUIPMENT",
            exchange: "NYSE",
            currency: "USD"
        },
        addedAt: new Date().toLocaleDateString(),
        timeSeries: {
            "metaData": {
                "frequency": TimeSeriesFrequence.DAILY
            },
            "series": {
                "2024-12-02": {
                    "open": 227.5,
                        "high": 228.38,
                        "low": 225.51,
                        "volume": 2644250,
                        "close": 227.39
                },
                "2024-11-29": {
                    "open": 227.75,
                        "high": 230.36,
                        "low": 227.19,
                        "volume": 2640253,
                        "close": 227.41
                },
                "2024-11-27": {
                    "open": 228.83,
                        "high": 229.19,
                        "low": 224.27,
                        "volume": 2995121,
                        "close": 226.92
                },
                "2024-11-26": {
                    "open": 226.73,
                        "high": 228.98,
                        "low": 225.5115,
                        "volume": 4449543,
                        "close": 228.83
                },
                "2024-11-25": {
                    "open": 223.35,
                        "high": 226.42,
                        "low": 222.65,
                        "volume": 7189260,
                        "close": 226.13
                },
                "2024-11-22": {
                    "open": 223.35,
                        "high": 227.2,
                        "low": 220.89,
                        "volume": 5320740,
                        "close": 222.97
                },
                "2024-11-21": {
                    "open": 215.81,
                        "high": 222.63,
                        "low": 215.2701,
                        "volume": 5236434,
                        "close": 222.4
                },
                "2024-11-20": {
                    "open": 211,
                        "high": 214.96,
                        "low": 209.7725,
                        "volume": 4562901,
                        "close": 214.6
                },
                "2024-11-19": {
                    "open": 206.5,
                        "high": 210.33,
                        "low": 206.19,
                        "volume": 2860746,
                        "close": 210.25
                },
                "2024-11-18": {
                    "open": 207,
                        "high": 208.415,
                        "low": 205.3701,
                        "volume": 3406045,
                        "close": 208.09
                },
                "2024-11-15": {
                    "open": 207.46,
                        "high": 208.49,
                        "low": 204.07,
                        "volume": 3986460,
                        "close": 204.99
                },
                "2024-11-14": {
                    "open": 210,
                        "high": 210.4999,
                        "low": 206.35,
                        "volume": 6372853,
                        "close": 208.99
                },
                "2024-11-13": {
                    "open": 209.5,
                        "high": 211.41,
                        "low": 209.0701,
                        "volume": 3247830,
                        "close": 210.92
                },
                "2024-11-12": {
                    "open": 211.9,
                        "high": 213.03,
                        "low": 209.06,
                        "volume": 2818216,
                        "close": 210.86
                },
                "2024-11-11": {
                    "open": 214.4,
                        "high": 215.41,
                        "low": 213.48,
                        "volume": 3012987,
                        "close": 213.57
                },
                "2024-11-08": {
                    "open": 214.16,
                        "high": 216.7,
                        "low": 212.7809,
                        "volume": 3201038,
                        "close": 213.72
                },
                "2024-11-07": {
                    "open": 213.64,
                        "high": 214.5199,
                        "low": 211.93,
                        "volume": 3675812,
                        "close": 213.69
                },
                "2024-11-06": {
                    "open": 213.48,
                        "high": 214.33,
                        "low": 210.37,
                        "volume": 3934386,
                        "close": 213.6
                },
                "2024-11-05": {
                    "open": 206.17,
                        "high": 208.115,
                        "low": 205.57,
                        "volume": 2441535,
                        "close": 207.57
                },
                "2024-11-04": {
                    "open": 207.65,
                        "high": 207.7,
                        "low": 205.8,
                        "volume": 2594119,
                        "close": 206.32
                },
                "2024-11-01": {
                    "open": 207.77,
                        "high": 209.84,
                        "low": 207.41,
                        "volume": 3334308,
                        "close": 208.25
                },
                "2024-10-31": {
                    "open": 204.13,
                        "high": 208.13,
                        "low": 203.51,
                        "volume": 5925250,
                        "close": 206.72
                },
                "2024-10-30": {
                    "open": 209.48,
                        "high": 211.12,
                        "low": 204.26,
                        "volume": 6956624,
                        "close": 204.9
                },
                "2024-10-29": {
                    "open": 211.99,
                        "high": 213.34,
                        "low": 209.85,
                        "volume": 5258366,
                        "close": 210.43
                },
                "2024-10-28": {
                    "open": 215.5,
                        "high": 216.25,
                        "low": 212.7,
                        "volume": 4993343,
                        "close": 212.91
                },
                "2024-10-25": {
                    "open": 216.8,
                        "high": 218.65,
                        "low": 214.385,
                        "volume": 8482235,
                        "close": 214.67
                },
                "2024-10-24": {
                    "open": 220.8,
                        "high": 221.32,
                        "low": 216.16,
                        "volume": 11193440,
                        "close": 218.39
                },
                "2024-10-23": {
                    "open": 230.41,
                        "high": 233.34,
                        "low": 230.26,
                        "volume": 5791002,
                        "close": 232.75
                },
                "2024-10-22": {
                    "open": 231.99,
                        "high": 232.97,
                        "low": 230.67,
                        "volume": 3180807,
                        "close": 232.25
                },
                "2024-10-21": {
                    "open": 231.21,
                        "high": 232.42,
                        "low": 230.26,
                        "volume": 2733336,
                        "close": 231.75
                },
                "2024-10-18": {
                    "open": 231.92,
                        "high": 232.6499,
                        "low": 230.17,
                        "volume": 4715688,
                        "close": 232.2
                },
                "2024-10-17": {
                    "open": 232,
                        "high": 233.145,
                        "low": 230.655,
                        "volume": 5040092,
                        "close": 232.88
                },
                "2024-10-16": {
                    "open": 232.11,
                        "high": 233.88,
                        "low": 231.12,
                        "volume": 2846669,
                        "close": 233.67
                },
                "2024-10-15": {
                    "open": 236.4,
                        "high": 237.37,
                        "low": 232.71,
                        "volume": 3350556,
                        "close": 232.96
                },
                "2024-10-14": {
                    "open": 233.57,
                        "high": 236.12,
                        "low": 233.17,
                        "volume": 2524389,
                        "close": 235.26
                },
                "2024-10-11": {
                    "open": 233.25,
                        "high": 233.44,
                        "low": 230.46,
                        "volume": 3469322,
                        "close": 233.26
                },
                "2024-10-10": {
                    "open": 235.1,
                        "high": 235.83,
                        "low": 231.81,
                        "volume": 3142031,
                        "close": 233.02
                },
                "2024-10-09": {
                    "open": 229.2,
                        "high": 234.95,
                        "low": 228.5,
                        "volume": 5083566,
                        "close": 234.3
                },
                "2024-10-08": {
                    "open": 228.11,
                        "high": 229.345,
                        "low": 227.0401,
                        "volume": 3245342,
                        "close": 228.62
                },
                "2024-10-07": {
                    "open": 225.38,
                        "high": 227.67,
                        "low": 225.02,
                        "volume": 3457952,
                        "close": 227.12
                },
                "2024-10-04": {
                    "open": 223.75,
                        "high": 226.08,
                        "low": 223.27,
                        "volume": 3554328,
                        "close": 226
                },
                "2024-10-03": {
                    "open": 219.5,
                        "high": 222.83,
                        "low": 219.27,
                        "volume": 3788265,
                        "close": 222.72
                },
                "2024-10-02": {
                    "open": 218.31,
                        "high": 220.2,
                        "low": 215.798,
                        "volume": 3343399,
                        "close": 219.73
                },
                "2024-10-01": {
                    "open": 220.63,
                        "high": 221.1,
                        "low": 215.9,
                        "volume": 3548374,
                        "close": 219.35
                },
                "2024-09-30": {
                    "open": 220.65,
                        "high": 221.32,
                        "low": 219.02,
                        "volume": 3544264,
                        "close": 221.08
                },
                "2024-09-27": {
                    "open": 223,
                        "high": 224.15,
                        "low": 220.77,
                        "volume": 3830335,
                        "close": 220.84
                },
                "2024-09-26": {
                    "open": 222.11,
                        "high": 224,
                        "low": 221.355,
                        "volume": 2673210,
                        "close": 223.43
                },
                "2024-09-25": {
                    "open": 221.17,
                        "high": 221.85,
                        "low": 220.16,
                        "volume": 2537751,
                        "close": 221.23
                },
                "2024-09-24": {
                    "open": 219.78,
                        "high": 221.19,
                        "low": 218.16,
                        "volume": 3184114,
                        "close": 220.97
                },
                "2024-09-23": {
                    "open": 218,
                        "high": 220.62,
                        "low": 217.27,
                        "volume": 4074755,
                        "close": 220.5
                },
                "2024-09-20": {
                    "open": 214.33,
                        "high": 217.85,
                        "low": 213.74,
                        "volume": 9958980,
                        "close": 217.7
                },
                "2024-09-19": {
                    "open": 218.01,
                        "high": 218.48,
                        "low": 210.37,
                        "volume": 5279559,
                        "close": 213.89
                },
                "2024-09-18": {
                    "open": 214.13,
                        "high": 216.86,
                        "low": 213.59,
                        "volume": 3482764,
                        "close": 214.94
                },
                "2024-09-17": {
                    "open": 217.25,
                        "high": 218.84,
                        "low": 213,
                        "volume": 5635210,
                        "close": 214.13
                },
                "2024-09-16": {
                    "open": 215.88,
                        "high": 217.9,
                        "low": 215.52,
                        "volume": 4176257,
                        "close": 217.16
                },
                "2024-09-13": {
                    "open": 212.48,
                        "high": 216.09,
                        "low": 212.13,
                        "volume": 4572344,
                        "close": 214.79
                },
                "2024-09-12": {
                    "open": 210,
                        "high": 212.65,
                        "low": 208.265,
                        "volume": 4616446,
                        "close": 211.61
                },
                "2024-09-11": {
                    "open": 207.76,
                        "high": 210.12,
                        "low": 203.04,
                        "volume": 5554309,
                        "close": 209.89
                },
                "2024-09-10": {
                    "open": 204.2,
                        "high": 205.83,
                        "low": 202.87,
                        "volume": 3070644,
                        "close": 205.32
                },
                "2024-09-09": {
                    "open": 201.94,
                        "high": 205.05,
                        "low": 201.43,
                        "volume": 3705004,
                        "close": 203.53
                },
                "2024-09-06": {
                    "open": 202.38,
                        "high": 204.1,
                        "low": 199.335,
                        "volume": 3304491,
                        "close": 200.74
                },
                "2024-09-05": {
                    "open": 204.08,
                        "high": 205.95,
                        "low": 200.96,
                        "volume": 3229345,
                        "close": 202.59
                },
                "2024-09-04": {
                    "open": 200.76,
                        "high": 204.36,
                        "low": 200.5,
                        "volume": 3111332,
                        "close": 204.11
                },
                "2024-09-03": {
                    "open": 201.91,
                        "high": 204.72,
                        "low": 200.21,
                        "volume": 3874697,
                        "close": 201.28
                },
                "2024-08-30": {
                    "open": 199.11,
                        "high": 202.17,
                        "low": 198.73,
                        "volume": 4750999,
                        "close": 202.13
                },
                "2024-08-29": {
                    "open": 199.3,
                        "high": 201.12,
                        "low": 198.27,
                        "volume": 2989594,
                        "close": 198.9
                },
                "2024-08-28": {
                    "open": 199,
                        "high": 200,
                        "low": 197.49,
                        "volume": 2645244,
                        "close": 198.46
                },
                "2024-08-27": {
                    "open": 197.44,
                        "high": 199.4,
                        "low": 196.97,
                        "volume": 2617229,
                        "close": 198.73
                },
                "2024-08-26": {
                    "open": 196,
                        "high": 198.345,
                        "low": 195.9,
                        "volume": 2567217,
                        "close": 197.98
                },
                "2024-08-23": {
                    "open": 196.79,
                        "high": 197.38,
                        "low": 194.39,
                        "volume": 2321961,
                        "close": 196.1
                },
                "2024-08-22": {
                    "open": 197.25,
                        "high": 197.92,
                        "low": 195.57,
                        "volume": 1969496,
                        "close": 195.96
                },
                "2024-08-21": {
                    "open": 195.97,
                        "high": 197.33,
                        "low": 194.115,
                        "volume": 2579343,
                        "close": 197.21
                },
                "2024-08-20": {
                    "open": 194.59,
                        "high": 196.21,
                        "low": 193.75,
                        "volume": 1790371,
                        "close": 196.03
                },
                "2024-08-19": {
                    "open": 193.84,
                        "high": 195.525,
                        "low": 193.715,
                        "volume": 2361378,
                        "close": 194.73
                },
                "2024-08-16": {
                    "open": 193.58,
                        "high": 194.35,
                        "low": 192.86,
                        "volume": 2494472,
                        "close": 193.78
                },
                "2024-08-15": {
                    "open": 193.51,
                        "high": 194.25,
                        "low": 193.28,
                        "volume": 2471985,
                        "close": 193.95
                },
                "2024-08-14": {
                    "open": 191.15,
                        "high": 193.09,
                        "low": 190.73,
                        "volume": 1895114,
                        "close": 192.32
                },
                "2024-08-13": {
                    "open": 190.29,
                        "high": 191.31,
                        "low": 189.21,
                        "volume": 2178862,
                        "close": 190.99
                },
                "2024-08-12": {
                    "open": 191.25,
                        "high": 191.5761,
                        "low": 189.0001,
                        "volume": 2290421,
                        "close": 189.48
                },
                "2024-08-09": {
                    "open": 191.18,
                        "high": 192.63,
                        "low": 189.04,
                        "volume": 2773706,
                        "close": 191.45
                },
                "2024-08-08": {
                    "open": 187.5,
                        "high": 192.88,
                        "low": 187,
                        "volume": 3712698,
                        "close": 192.61
                },
                "2024-08-07": {
                    "open": 188.08,
                        "high": 189.87,
                        "low": 186.7,
                        "volume": 3801942,
                        "close": 186.8
                },
                "2024-08-06": {
                    "open": 184.7,
                        "high": 188.9,
                        "low": 183.64,
                        "volume": 3632517,
                        "close": 186.8
                },
                "2024-08-05": {
                    "open": 184.55,
                        "high": 185.255,
                        "low": 181.81,
                        "volume": 4975002,
                        "close": 183.31
                },
                "2024-08-02": {
                    "open": 188.78,
                        "high": 189.26,
                        "low": 185.7,
                        "volume": 4548824,
                        "close": 189.12
                },
                "2024-08-01": {
                    "open": 192.81,
                        "high": 193.635,
                        "low": 188.29,
                        "volume": 4085354,
                        "close": 189.66
                },
                "2024-07-31": {
                    "open": 191,
                        "high": 194.5499,
                        "low": 189.99,
                        "volume": 5558405,
                        "close": 192.14
                },
                "2024-07-30": {
                    "open": 191.48,
                        "high": 192.77,
                        "low": 189.09,
                        "volume": 3064978,
                        "close": 191.04
                },
                "2024-07-29": {
                    "open": 193.18,
                        "high": 193.29,
                        "low": 189.18,
                        "volume": 3336806,
                        "close": 191.5
                },
                "2024-07-26": {
                    "open": 190.51,
                        "high": 193.57,
                        "low": 189.622,
                        "volume": 4294875,
                        "close": 191.75
                },
                "2024-07-25": {
                    "open": 186.8,
                        "high": 196.26,
                        "low": 185.3,
                        "volume": 9532802,
                        "close": 191.98
                },
                "2024-07-24": {
                    "open": 184.14,
                        "high": 185.0714,
                        "low": 183.145,
                        "volume": 6962071,
                        "close": 184.02
                },
                "2024-07-23": {
                    "open": 184.36,
                        "high": 185.38,
                        "low": 183.01,
                        "volume": 2180225,
                        "close": 184.1
                },
                "2024-07-22": {
                    "open": 183.4,
                        "high": 184.97,
                        "low": 182.86,
                        "volume": 2488525,
                        "close": 184.15
                },
                "2024-07-19": {
                    "open": 186.33,
                        "high": 187,
                        "low": 181.95,
                        "volume": 3816039,
                        "close": 183.25
                },
                "2024-07-18": {
                    "open": 186.64,
                        "high": 189.47,
                        "low": 185.1,
                        "volume": 3487808,
                        "close": 185.22
                },
                "2024-07-17": {
                    "open": 185.44,
                        "high": 187.94,
                        "low": 185.07,
                        "volume": 4225302,
                        "close": 187.45
                },
                "2024-07-16": {
                    "open": 184.67,
                        "high": 186.6,
                        "low": 184.52,
                        "volume": 3374526,
                        "close": 185.81
                },
                "2024-07-15": {
                    "open": 183.38,
                        "high": 184.9,
                        "low": 182.6,
                        "volume": 2925794,
                        "close": 182.88
                },
                "2024-07-12": {
                    "open": 178.56,
                "high": 184.16,
                "low": 178.5,
                "volume": 4785565,
                "close": 182.83
        }
    }
},
        globalQuote: {
            open: 170.4400,
            high: 171.0850,
            low: 168.6500,
            price: 169.6600,
            volume: 2627584,
            latestTradingDay: moment("2024-05-28"),
            previousClose: 170.8900,
            change: -1.2300,
            changePercent: "-0.7198%"
        }
    }
]
