services:
  database:
    image: postgres:14-alpine
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_DB: stocks
      POSTGRES_USER: stocks
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "stocks" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    
  redis:
    image: redis:7.4.1-alpine
    command: ["redis-server", "--save 60 1", "--loglevel warning"]
    restart: always
    ports:
      - 6379:6379
    volumes: 
      - ./redis/data:/data
