services:
  database:
    image: postgres:12.19-alpine3.20
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_DB: stocks
      POSTGRES_USER: stocks
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "stocks" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
